:verbose: false
:concurrency:  10
:queues:
  - [rollbacks, 2]
  - [sync, 2]
  - [default, 5]
:schedule:
  #
  # Syntax:
  #
  # mm hh dd mt wd  command
  #
  # mm minute 0-59
  # hh hour 0-23
  # dd day of month 1-31
  # mt month 1-12
  # wd day of week 0-7 (Sunday = 0 or 7)
  #
  # Online converter: https://crontab.guru/#0_22_*_*_*
  #
  UpdatesSynchronizerWorker:
    cron: "0 22 * * *" # 10 PM every day
    description: "UpdatesSynchronizerWorker will run every day at 10pm."
  TaricSequenceCheckWorker:
    cron: "0 14 * * 6" # 14:00 every Saturday
    description: "TaricSequenceCheckWorker will run every Saturday at 14:00."
  ClearCacheWorker:
    cron: "0 0 * * *" # 00:00 every day
    description: "Clear Rails cache at midnight"
  RecacheModelsWorker:
    cron: "0 1 * * *" # 01:00 every day
    description: "RecacheModelsWorker will run every day at 1am."
  ReindexModelsWorker:
    cron: "0 1 * * *" # 01:00 every day
    description: "ReindexModelsWorker will run every day at 1am."
  RunChapterPdfWorker:
    cron: "0 5 * * *" # 05:00 every day
    description: "RunChapterPdfWorker produces the Tariff PDF."
    args: [['EUR', 'GBP']]
