:verbose: false
:concurrency:  1
:queues:
  - [rollbacks, 2]
  - [sync, 2]
  - [default, 5]
:schedule:
  UpdatesSynchronizerWorker:
    cron: "0 20,23 * * *"
    description: "This job will run at 20:00 and 23:00 every day."
