:verbose: false
:concurrency:  12
:queues:
  - [rollbacks, 2]
  - [sync, 2]
  - [default, 5]
:schedule:
  #
  # Syntax:
  #
  # mm hh dd mt wd  command
  #
  # mm minute 0-59
  # hh hour 0-23
  # dd day of month 1-31
  # mt month 1-12
  # wd day of week 0-7 (Sunday = 0 or 7)
  #
  # Online converter: https://crontab.guru/#0_22_*_*_*
  #
  UpdatesSynchronizerWorker:
    cron: "0 22 * * *" # 10 PM every days
    description: "UpdatesSynchronizerWorker will run every day at 10pm."
  RecacheModelsWorker:
    cron: "0 0 * * *" # 0 AM every day
    description: "RecacheModelsWorker will run every day at 0am."
  ReindexModelsWorker:
    cron: "0 0 * * *" # 0 AM every day
    description: "ReindexModelsWorker will run every day at 0am."
  RunChapterPdfWorker:
    cron: "0 2 * * *" # 2 AM every day
    description: "RunChapterPdfWorker produces the Tariff PDF."
