:verbose: false
:concurrency:  1
:queues:
  - [rollbacks, 2]
  - [sync, 2]
  - [default, 5]
:schedule:
  UpdatesSynchronizerWorker:
    cron: "0 * * * *"
    description: "This job will run every hour, every day."
  ReindexModelsWorker:
    cron: "0 1 * * *"
    description: "This job will run at 01:00 every day."
