return unless ENV['RUNNING_TASK']

forum_links = [
  {:chapter=>"01", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/01/8"},
  {:chapter=>"02", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/02/10"},
  {:chapter=>"03", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/03/11"},
  {:chapter=>"04", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/04/12"},
  {:chapter=>"05", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/05/13"},
  {:chapter=>"06", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/06/14"},
  {:chapter=>"07", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/07/15"},
  {:chapter=>"08", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/08/16"},
  {:chapter=>"09", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/09/17"},
  {:chapter=>"10", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/10/18"},
  {:chapter=>"11", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/11/19"},
  {:chapter=>"12", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/12/20"},
  {:chapter=>"13", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/13/21"},
  {:chapter=>"14", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/14/22"},
  {:chapter=>"15", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/15/23"},
  {:chapter=>"16", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/16/24"},
  {:chapter=>"17", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/17/25"},
  {:chapter=>"18", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/18/26"},
  {:chapter=>"19", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/19/27"},
  {:chapter=>"20", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/20/28"},
  {:chapter=>"21", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/21/29"},
  {:chapter=>"22", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/22/30"},
  {:chapter=>"23", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/23/31"},
  {:chapter=>"24", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/24/32"},
  {:chapter=>"25", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/25/33"},
  {:chapter=>"26", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/26/34"},
  {:chapter=>"27", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/27/35"},
  {:chapter=>"28", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/28/36"},
  {:chapter=>"29", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/29/37"},
  {:chapter=>"30", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/30/38"},
  {:chapter=>"31", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/31/39"},
  {:chapter=>"32", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/32/40"},
  {:chapter=>"33", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/33/41"},
  {:chapter=>"34", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/34/42"},
  {:chapter=>"35", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/35/43"},
  {:chapter=>"36", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/36/44"},
  {:chapter=>"37", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/37/45"},
  {:chapter=>"38", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/38/9"},
  {:chapter=>"39", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/39/46"},
  {:chapter=>"40", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/40/47"},
  {:chapter=>"41", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/41/48"},
  {:chapter=>"42", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/42/49"},
  {:chapter=>"43", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/43/50"},
  {:chapter=>"44", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/44/51"},
  {:chapter=>"45", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/45/52"},
  {:chapter=>"46", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/46/53"},
  {:chapter=>"47", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/47/54"},
  {:chapter=>"48", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/48/55"},
  {:chapter=>"49", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/49/56"},
  {:chapter=>"50", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/50/57"},
  {:chapter=>"51", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/51/58"},
  {:chapter=>"52", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/52/59"},
  {:chapter=>"53", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/53/60"},
  {:chapter=>"54", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/54/61"},
  {:chapter=>"55", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/55/62"},
  {:chapter=>"56", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/56/63"},
  {:chapter=>"57", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/57/64"},
  {:chapter=>"58", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/58/65"},
  {:chapter=>"59", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/59/66"},
  {:chapter=>"60", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/60/67"},
  {:chapter=>"61", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/61/68"},
  {:chapter=>"62", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/62/69"},
  {:chapter=>"63", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/63/70"},
  {:chapter=>"64", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/64/71"},
  {:chapter=>"65", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/65/72"},
  {:chapter=>"66", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/66/73"},
  {:chapter=>"67", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/67/74"},
  {:chapter=>"68", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/68/75"},
  {:chapter=>"69", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/69/76"},
  {:chapter=>"70", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/70/77"},
  {:chapter=>"71", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/71/78"},
  {:chapter=>"72", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/72/79"},
  {:chapter=>"73", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/73/80"},
  {:chapter=>"74", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/74/81"},
  {:chapter=>"75", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/75/82"},
  {:chapter=>"76", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/76/83"},
  # {:chapter=>"77", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/77/84"},
  {:chapter=>"78", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/78/85"},
  {:chapter=>"79", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/79/86"},
  {:chapter=>"80", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/80/87"},
  {:chapter=>"81", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/81/88"},
  {:chapter=>"82", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/82/89"},
  {:chapter=>"83", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/83/90"},
  {:chapter=>"84", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/84/91"},
  {:chapter=>"85", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/85/92"},
  {:chapter=>"86", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/86/93"},
  {:chapter=>"87", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/87/94"},
  {:chapter=>"88", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/88/95"},
  {:chapter=>"89", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/89/96"},
  {:chapter=>"90", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/90/97"},
  {:chapter=>"91", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/91/98"},
  {:chapter=>"92", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/92/99"},
  {:chapter=>"93", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/93/100"},
  {:chapter=>"94", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/94/101"},
  {:chapter=>"95", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/95/102"},
  {:chapter=>"96", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/96/103"},
  {:chapter=>"97", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/97/104"},
  {:chapter=>"98", :url=>"https://forum.trade-tariff.service.gov.uk/c/classification/98/105"}
]


forum_links.each do |link|
  chapter = Chapter.where(goods_nomenclature_item_id: "#{link[:chapter]}00000000").last
  if chapter
    ForumLink.create(goods_nomenclature_sid: chapter.goods_nomenclature_sid, url: link[:url])
  end
end
