name: "Production deployment"
on: [workflow_dispatch]
jobs:
  deploy_production:
    if: github.ref == 'refs/heads/production_notyet'
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5.8
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: "Deploy production"
        env:
          CF_ENDPOINT: "api.london.cloud.service.gov.uk"
          CF_SPACE: production
          CF_APP: "tariff-backend-production"
          CF_APP_WORKER: "tariff-backend-worker-production"
          CF_USER: ${{ secrets.CF_USER }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
          CF_ORG: ${{ secrets.CF_ORG }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          HEALTHCHECK_URL: ${{ secrets.HEALTHCHECK_URL }}
        run: |
          curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
          sudo dpkg -i cf-cli_amd64.deb
          cf -v
          cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org
          cf install-plugin blue-green-deploy -r CF-Community -f
          cf install-plugin app-autoscaler-plugin -r CF-Community -f
          ./bin/deploy